# Generated by Django 5.2.7 on 2025-10-28 21:23

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemTemplate',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('cost', models.IntegerField()),
                ('description', models.TextField()),
                ('sprite_path', models.CharField(max_length=255)),
                ('api_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='PokemonSpecies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pokedex_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=50)),
                ('types', models.JSONField()),
                ('stats', models.JSONField()),
                ('ability', models.CharField(max_length=50)),
                ('hidden_ability', models.CharField(blank=True, max_length=50)),
                ('sprite', models.CharField(max_length=200)),
                ('gender_rate', models.IntegerField(blank=True, null=True)),
                ('has_gender_differences', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('nickname', models.CharField(max_length=30)),
                ('pokedollars', models.IntegerField(default=10000)),
                ('pokediamonds', models.IntegerField(default=0)),
                ('level', models.IntegerField(default=1)),
                ('role', models.CharField(default='player', max_length=20)),
                ('experience', models.IntegerField(default=0)),
                ('experience_to_next_level', models.IntegerField(default=100)),
                ('starter', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, related_name='custom_user_set', to='auth.group')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='custom_user_permissions_set', to='auth.permission')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='game.itemtemplate')),
            ],
        ),
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(blank=True, max_length=50)),
                ('level', models.IntegerField(default=5)),
                ('experience', models.IntegerField(default=0)),
                ('experience_to_next_level', models.IntegerField(default=100)),
                ('shiny', models.BooleanField(default=False)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('genderless', 'Genderless')], max_length=10, null=True)),
                ('slot', models.PositiveSmallIntegerField(default=0)),
                ('ivs', models.JSONField()),
                ('nature', models.CharField(max_length=20)),
                ('stats', models.JSONField(default=dict)),
                ('current_hp', models.IntegerField(default=0)),
                ('active', models.BooleanField(default=False)),
                ('caught_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pokemons', to=settings.AUTH_USER_MODEL)),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='game.pokemonspecies')),
            ],
        ),
        migrations.CreateModel(
            name='PokemonBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('box_number', models.IntegerField(default=1)),
                ('position', models.IntegerField(default=1)),
                ('pokemon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.pokemon')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pc_pokemons', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_category', models.CharField(choices=[('pokeballs', 'Poké Balls'), ('healing', 'Medicinas'), ('battle_items', 'Objetos de Batalla'), ('berries', 'Berries'), ('evolution', 'Objetos de Evolución'), ('key_items', 'Objetos Clave'), ('treasures', 'Tesoros')], max_length=50)),
                ('stock', models.IntegerField(default=9999, help_text='Stock disponible (9999 = ilimitado)')),
                ('available', models.BooleanField(default=True)),
                ('discount', models.FloatField(default=0.0, help_text='Porcentaje de descuento (0.1 = 10%)')),
                ('item_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop_entries', to='game.itemtemplate')),
            ],
        ),
    ]
