# Generated by Django 5.2.7 on 2025-10-28 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_create_itemtemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemtemplate',
            name='heal_amount',
            field=models.IntegerField(default=0, help_text='Cantidad de HP que cura si aplica'),
        ),
        migrations.AddField(
            model_name='itemtemplate',
            name='is_equipable',
            field=models.BooleanField(default=False, help_text='Indica si puede equiparse a un Pokémon'),
        ),
        migrations.AddField(
            model_name='itemtemplate',
            name='is_healing',
            field=models.BooleanField(default=False, help_text='Indica si el ítem puede curar HP'),
        ),
    ]
