# Generated by Django 5.2.7 on 2025-10-29 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_itemtemplate_heal_amount_itemtemplate_is_equipable_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemtemplate',
            name='capture_rate',
            field=models.FloatField(default=0.0, help_text='Multiplicador de captura si es una Poké Ball'),
        ),
    ]
