# Generated by Django 5.2.7 on 2025-10-29 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_itemtemplate_capture_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='slot_pc',
            field=models.PositiveIntegerField(default=1, help_text='Orden del Pokémon en el PC Box'),
        ),
    ]
