# Generated by Django 5.2.7 on 2025-10-29 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_pokemon_slot_pc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='slot_pc',
            field=models.PositiveIntegerField(default=0, help_text='Orden del Pokémon en el PC Box'),
        ),
    ]
