# Generated by Django 5.2.7 on 2025-10-30 01:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_alter_pokemon_slot_pc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Move',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('type', models.CharField(max_length=50)),
                ('category', models.CharField(choices=[('physical', 'Physical'), ('special', 'Special'), ('status', 'Status')], max_length=20)),
                ('power', models.IntegerField(blank=True, null=True)),
                ('accuracy', models.IntegerField(blank=True, null=True)),
                ('pp', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('api_url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PokemonCurrentMove',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot', models.IntegerField()),
                ('move', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.move')),
                ('pokemon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='current_moves', to='game.pokemon')),
            ],
            options={
                'unique_together': {('pokemon', 'slot')},
            },
        ),
        migrations.CreateModel(
            name='PokemonMove',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_learned_at', models.IntegerField(default=0)),
                ('learn_method', models.CharField(default='unknown', max_length=50)),
                ('move', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.move')),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moves', to='game.pokemonspecies')),
            ],
            options={
                'unique_together': {('species', 'move', 'learn_method')},
            },
        ),
    ]
