# Generated by Django 5.2.7 on 2025-10-30 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_move_pokemoncurrentmove_pokemonmove'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemoncurrentmove',
            name='pp_current',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pokemoncurrentmove',
            name='pp_max',
            field=models.IntegerField(default=0),
        ),
    ]
