# Generated by Django 5.2.7 on 2025-10-30 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_pokemoncurrentmove_pp_current_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='slot',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
