# Generated by Django 5.2.7 on 2025-11-13 00:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_alter_pokemon_slot'),
    ]

    operations = [
        migrations.CreateModel(
            name='GachaBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField(default=0)),
                ('description', models.TextField(blank=True)),
                ('banner', models.URLField(blank=True, null=True)),
                ('category', models.CharField(default='General', max_length=50)),
                ('available', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='GachaPool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rarity', models.CharField(choices=[('common', 'Comun'), ('rare', 'Rara'), ('epic', 'Épica'), ('legendary', 'Legendaria'), ('shiny', 'Shiny')], max_length=20)),
                ('shiny_chance', models.FloatField(default=0.01)),
                ('probability', models.FloatField(default=0.0)),
                ('box', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pool', to='game.gachabox')),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.pokemonspecies')),
            ],
        ),
    ]
